# create your drupal and postgres config here, based off the last assignment

services:
  drupal:
    build:
      context: .
      dockerfile: custom-drupal.Dockerfile
    ports:
      - "81:80"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: drupal
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
